### ISSUE TITLE
Feature: User can sign in to their account

### ISSUE THREAD

**Issue by mdoanle** [mdoanle/weight-tracker-fuze#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to sign into their own personal account using their own username and password

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After hitting the landing page/home page, the user will be able to press a button which will open up a log in screen, the user will input their username and password and when validated they will be redirected to the home page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106715675/200429745-8bcb95f0-00ae-48f4-9bf7-ec3fee7849a9.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [index.js]
-  [x] write a POST route with the path '.../.../sign-in'
-  [x] destructure the username and password from the request body
-  [x] ensure the user has filled in the username and password inputs
- [x] write up some sql code (` select "userId", "hashedPassword" from "Users" where username = $1)
- [x] create a params variable that is an array of our hidden data (const params = [username])
- [x] query the database using our sql and our params as arguments
- [x] then (*winkyface*), write a callback function that  destructures the user variable from the result.rows and then checks to see if it exists in our database.
- [x] If it does not, then return a 401 error and tell the client that theyve given us invalid data
- [x] if it does exists, then we must check to see if the password given matches what we have in our DB, which means we must use argon2 to verify
- [x] destructure userId and password from the user object
- [x] first we have to return argon2. verify using our hashedpassword on record and the password that the user gave us
- [x] then *winkyface*, we must write a callback function that takes the return of .verify(a boolean) and then test if the password we have been given was forged.
- [x] .then(isMatching => {if !isMatching = invalid log in, otherwise create payload object that has properties of userId and username, create a token variable that is assigned the return of a jwt.sign function with two arguments, the payload we made and the secret variable that only we know (process.env.TOKEN_SECRET)
- [x] call res.json with an object as an argument. The object will have two properties, token with the value of token and user with the value of the payload object.
- [x] remember that everything after this must go through authentication middleware
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

-Piggybacking off of the created auth form for sign up, we will make minor changes to fit the wireframe, most of the functionality will remain

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
