### ISSUE TITLE
Feature: User can sign up for an account

### ISSUE THREAD

**Issue by mdoanle** [mdoanle/weight-tracker-fuze#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account using a username and password of their choosing

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be required to log in before being able to use the application, if the user does not have an account they will be able to be directed to a sign in screen which will take their

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106715675/200404076-5a3cfb78-3970-41c6-b530-267a9073c1f9.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
      - [ ] take in a table called 'users' that has columns (username, password, userId, createdAt)
      - [ ] update 'entries' table to take in a userId column to connect the two tables together

### ☁️ Server Tasks

- [x] Update `server/index.js`
        - [ ] error-middleware client error files to catch errors
        - [ ] whip up a listen route  
        - [ ]  write a POST route to address '/api/auth/sign-up'. 
        - [ ] destructure the username and password from the req.body
        - [ ] ensure that the user fills out both username and password fields on submit as they are required
        - [ ] use the hash method of the imported argon2 object with an argument of the given password
        - [ ] (then *winkyface*), pass in the hash variable into the promise.
        - [ ] write some sql, `insert into "users" ('username', 'password')
                                            values ($1, $2) [this hides our actual data]
                                             returning "username", "userId", "createdAt"
        - [ ] Dont forget to make a params list that houses the hidden data (const params = [username, hash]
        - [ ] Query the database with the variable sql and the params list as arguments
                 -then (*winkyface*), write a callback that will return a 201 code and returns the newly minted username, userId, and created timestamp in JSON format
                 - result => {res.status(201).json(result.rows[0])}
        - [ ] make sure you are catching errors
        - [ ] make sure you are catching errors for the first promise chain
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component
        - [ ] Component class will have two states: one for the username and one for the password
        - [ ] Create an auth-form component that consists of two inputs that are for the user to input their desired password and username
        - [ ] create a handle change event listener that will update the state as the user inputs into the input element        
        - [ ] create handle submit event listener that calls the fetch function that will use the POST route and will then switch the window.location.hash to sign-in (which will prompt the user to now log in using their new credentials

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
