### ISSUE TITLE
Feature: User can log their current weight

### ISSUE THREAD

**Issue by mdoanle** [mdoanle/weight-tracker-fuze#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can enter their current weight, along with the date

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
The user will be able to enter a New Entry screen where they will be able to fill in their weight and the date.  They will be able to submit this form.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106715675/200431247-dbf592bb-fde2-4f59-adec-0735e43040f1.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] create a table titled 'entries' that will take in a date and a weight.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] create a POST route that has a route '/api/entries'
- [x] destructure the date and entries from the req.body object
- [x] check to see if date and entries are given (these are required) throw a new ClientError
- [x] whip up some sql code (const sql = `insert into "entries", values ($1, $2), returning *`
- [x] make a params variable with the value of $1 and $2
- [x] query the database with our sql code and our params as arguments
- [x] then (*winkyface*), write up a callback function that has one parameter result => 1)destructure entry from result.rows array
- [x] catch all potential errors
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ...
- [x] Create a new entry page
- [x] Itll need a nav bar component
- [x] and a form react element that will have an entry for weight and an entry for date
- [x] for date I will use another npm package that will give the user a calendar to choose from when they click on the date input
- [x] Create a handle submit event listener that will call the fetch function to add the entry to the entries db
- [x] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
