### ISSUE TITLE
Feature: User can see their previously logged weight entries 

### ISSUE THREAD

**Issue by mdoanle** [mdoanle/weight-tracker-fuze#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can now see their history of logged weights, in reverse chronological order.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After logging in, the user will be able to have access to a home screen which will list out their logged weights.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106715675/200432287-b1031bc0-87c9-4a55-b3a1-5f0eb53fb235.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Write a GET route that grabs the weight and date columns of my entries database
- [x] I will need to grab the rows by entryID in descending order as to grab it in chronological order
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a home page
- [x] this will include a navbar and a welcome message along with a card that will display all of the weight entries
- [x] Have an entries state that will be set to an empty array
- [x] Write a componentDidMount method that will fetch (GET route) from the database and assign the data to the entries state.
- [x] Write an Entry component that will return a single entry from the database
- [x] Write an EntriesCard that will map through the entries state and return an Entries React element for each element in the array
- [x] Mount the EntriesCard to the App React component
- [x] Create a button that switches views back to the newEntry form
- [x] Style as needed

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
