### ISSUE TITLE
Feature: User can delete an entry

### ISSUE THREAD

**Issue by mdoanle** [mdoanle/weight-tracker-fuze#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to delete unwanted or incorrect entries into their weight loss log.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the homepage, next to each entry there will be a small symbol that will indicate deletion.  If the user clicks on the symbol a confirmation message will appear after which the entry will be deleted.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106715675/200433070-748be1bf-69e2-4087-bf42-25b6af87223c.png)
![image](https://user-images.githubusercontent.com/106715675/200433136-c949347c-543c-4383-a17e-4186e75b0567.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Create a DELETE route that takes in a path name '/api/entries/:entryId'
- [x] Write some sql code that will delete the row where entryId is equal to the entryId of the selected entry
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Add an icon in each Entry react element
- [x] Add an onClick event listener onto the icon
- [x] The event listener will display a modal, confirming deletion
- [x] Attach another onClick event listener to the confirmation button
- [x] Event listener for this onClick event will call a Fetch function that will use the DELETE route created prior.
- [x] Will use the entryId to determine which row needs to be deleted from the database
- [x] style as needed

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
