### ISSUE TITLE
Feature: User can upload photos of themselves

### ISSUE THREAD

**Issue by mdoanle** [mdoanle/weight-tracker-fuze#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can now upload photos to their weight entries

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the previously created New Entry page, there will now be an option to upload files. Along with a preview of the uploaded file.

On the New Entries 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106715675/200437190-74716cbe-c2f4-4221-85a8-27b73c980a5f.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update table to take in a new column (imageUrl)

### ☁️ Server Tasks

- [x] npm install multer
- [x] create uploads middleware.js
- [x] make an images folder in server/public directory
- [x] Update my POST route to be able to take in the new imageUrl from the req body.
- [x] this includes: updating the sql code, updating the params array, creating a url variable
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] update entry-form.jsx
- [x] Create a file input ref for the file input react element
- [x] update handleSubmit route
- [x] Instead of the request body being just the state, create a new FormData object and fill it with the ref, and the two states for date and weight.
- [x] then (wink wink) parse response
- [x] then reset state back to empty strings and reset the ref back to null
- [x] catch any errors
- [x] Update the render method to now render a file input form react element
- [x] create an image react element (that will act as an image preview) whos src will be the value of the uploaded file.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
