### ISSUE TITLE
Feature: User can see the photos that they have uploaded in the past

### ISSUE THREAD

**Issue by mdoanle** [mdoanle/weight-tracker-fuze#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can now see all previously uploaded photos.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the previously created home page where the user could see previously logged weight entries, they can now see the photos that have been uploaded as well.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106715675/200438341-be8a8842-1e7f-4b10-8f4d-0e1b73dd4d8d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### Server Tasks
- [x] update POST route to account for whether or not the user provided an image.

### ⚡ Client Tasks

- [x] update Entry function to take in imageUrl from DB
- [x] return another column that will show the image that correlates with each weight entry
- [x] if no image was provided, show a placeholder image
- [x] ensure that image is sized appropriately
- [x] style as necessary

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
