### ISSUE TITLE
Feature: User can enlarge/view photos in a pop out

### ISSUE THREAD

**Issue by mdoanle** [mdoanle/weight-tracker-fuze#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can now enlarge and view photos by simply clicking on the image on the Home Page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the home page, if the user would like to view their uploaded image they simply need to click on their image preview to create a modal that shows the enlarged image.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106715675/200439051-ee90efcc-1c95-4469-8bcb-c23fc2b6dd10.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] add a modal react element to my home page
- [x] add a showModal method to change my showModal state to true
- [x] Pass through the showModal method as a prop to the Entry function component
- [x] add a onClick Listener to the image react element of the Entry component which will be the showModal method
- [x] Take the src attribute from the selected image, apply that src to the one inside of the lightbox.
- [x] Style as needed.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
