### ISSUE TITLE
Feature: User can view their progress illustrated by a line graph

### ISSUE THREAD

**Issue by mdoanle** [mdoanle/weight-tracker-fuze#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can now visualize their progress in the form of a line graph.  The line graph will update in real time as the user adds new weight entries.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

As the user adds more entries with their updated weight, a line graph will appear that will take the data provided and display itself for the user to see.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106715675/200440343-a84aa30e-f3f7-4f62-bf0c-6f6a2a9c7ae8.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] import ChartJs using npm install
- [x] import react-chartjs-2
- [x] import { Line } from react chartjs 2
- [x] create a new state that will hold the data for the chart (dates as labels and weight as data)
- [x] create a getData method that calls a GET request to the database
- [x] Work through the response object (either with forEach or in a loop)
- [x] Insert dates into its own array
- [x] insert weights into its own array
- [x] update the new chartData state with the labels array and the data array, along with all the necessary details for ChartJS (lineweight, bordercolor, fill, lineTension, etc)
- [x] call the getData method inside of the componentDidMount method
- [x] create a LineChart component with a prop data that assigned the value of the newly updated chartData state
- [x] Style as needed

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
